import {Suspense} from 'react';
import type {NextPage} from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';

const ContractData = dynamic(() => import('../components/ContractData'), {ssr: false});

import {ConnectButton} from '@rainbow-me/rainbowkit';

const Home: NextPage = () => {
  return (
    <Suspense>
      <div className="">
        <Head>
          <title>NFT Searching App</title>
          <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
          <link href="/favicon.ico" rel="icon" />
        </Head>

        <main className="flex flex-col items-center justify-center flex-1 min-h-screen py-16">
          <ConnectButton />
          <ContractData />
        </main>

        <footer className="flex flex-1 py-8 border-t border-gray-200">
          <a
            href="https://rainbow.me"
            rel="noopener noreferrer"
            target="_blank"
            className="flex items-center justify-center flex-grow"
          >
            Made with ❤️ by your frens at 🌈
          </a>
        </footer>
      </div>
    </Suspense>
  );
};

export default Home;
