name: Certora

on: 
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarnv1-dist-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarnv1-dist-

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set up JRE 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.7/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc
          wget https://github.com/ethereum/solidity/releases/download/v0.8.4/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.4
          wget https://github.com/ethereum/solidity/releases/download/v0.8.2/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.2
          wget https://github.com/ethereum/solidity/releases/download/v0.6.12/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc6.12    
          pip3 install certora-cli

      - name: Apply harnesses
        run: |
          chmod +x spec/scripts/*.sh
          spec/scripts/applyHarnesses.sh

      - name: Sanity Trident with Certora
        run: |
          # spec/scripts/sanityConstantProductPool.sh
          # spec/scripts/sanityHybridPool.sh
          # spec/scripts/sanityMasterDeployer.sh
          # spec/scripts/sanitySymbolicPool.sh
          # spec/scripts/sanityTridentRouter.sh

      - name: Verify Trident Router with Certora
        run: |
          spec/scripts/verifyTridentRouterSimple.sh
          spec/scripts/verifyTridentRouter.sh
      - name: Verify Constant Product Pool with Certora
        run: |
          spec/scripts/verifyConstantProductPool.sh
      - name: Verify Hybrid Pool with Certora
        run: |
          spec/scripts/verifyHybridPool.sh
      - name: Verify Trident Libraries with Certora
        run: |
           spec/scripts/verifyTridentMath.sh
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}